### ISSUE TITLE
Environment  Execution error inquiry

### ISSUE THREAD

**Issue by limhasic** [ProjectNUWA/DragNUWA#12]
1. Is it okay to create a conda environment and use pip? Doesn't it conflict with existing packages?
-> The environment was somehow managed.

file upload -> ok

but The moment you drag on the image

  File "DragNUWA_demo.py", line 314, in add_tracking_points
    cv2.circle(transparent_layer, tuple(track[0]), 5, (255, 0, 0, 255), -1)
IndexError: list index out of range

so many error boom

Please make the environment right.

happy 
Halloween

**Comment by masonintokyo** [comment]
don't drag just click.
1st click for a start point and 2nd click for a end point of an arrow.

**Comment by limhasic** [comment]
An error occurs the moment you click
